site_name: JERB Tracker

repo_url: https://github.com/rory652/3881-project/
repo_name: rory652/3881-project

edit_uri: ""

plugins:
  - macros
  - render_swagger

theme:
  name: material
  logo: img/icon.png
  favicon: img/icon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: default
    primary: deep purple
    accent: purple
  features:
    - navigation.tabs
    - navigation.tracking
    - toc.integrate 
    - navigation.expand

extra:
  generator: false

nav:
  - Home: index.md
  - Reference: 
      - reference/index.md
      - reference/endpoints.md
      - reference/requests.md
      - reference/account.md
  - About: 
      - about/index.md

markdown_extensions:
  - toc:
      toc_depth: 2
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.snippets
  - pymdownx.details
  - admonition
  - tables
