name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        docker-version: ["20.10.7"]

    steps:
      - uses: actions/checkout@v2
      - name: Create .env
        working-directory: ./source
        run: echo -en 'APP_KEY=app\nSESSION_PASS=session\nDB_PASS=db' > .env
      
      - name: Build the stack and run
        run: docker compose --profile test up --abort-on-container-exit --exit-code-from tests
